
package project2.pkg1;

import java.text.DecimalFormat;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public class Form extends javax.swing.JFrame {
    
    String price[]={"30","40","50","30","40","50","30","40","50","30","40","50","30","40","50","30","40","50","30","40","50","30","40","50","30","40","50","30","40","50","30","40","50",};    
    DefaultTableModel model;
    DecimalFormat df=new DecimalFormat("#,###.00");
    double total=0.0;
    int selected;
    int n;
    double change;
    double money;
    public Form() {
        initComponents();
        t1.setText(price[0]);
        model=(DefaultTableModel)tb.getModel();
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel6 = new javax.swing.JLabel();
        cbFood = new javax.swing.JComboBox<>();
        t1 = new javax.swing.JTextField();
        t2 = new javax.swing.JTextField();
        t3 = new javax.swing.JTextField();
        bn1 = new javax.swing.JButton();
        bn2 = new javax.swing.JButton();
        bn3 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tb = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        lbtotal = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        tchange = new javax.swing.JTextField();

        jLabel6.setText("jLabel6");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Smootie BOY");

        cbFood.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        cbFood.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Matcha Green Tea Frappe--[S]", "Matcha Green Tea Frappe--[M]", "Matcha Green Tea Frappe--[L]", "Houjicha Latte Frappe--[S]", "Houjicha Latte Frappe--[M]", "Houjicha Latte Frappe--[L]", "Coffee with Cookies & Cream Frappe--[S]", "Coffee with Cookies & Cream Frappe--[M]", "Coffee with Cookies & Cream Frappe--[L]", "Cocoa FrappeCocoa Oreo Frappe--[S]", "Cocoa FrappeCocoa Oreo Frappe--[M]", "Cocoa FrappeCocoa Oreo Frappe--[L]", "Thai Tea Frappe--[S]", "Thai Tea Frappe--[M]", "Thai Tea Frappe--[L]", "Milk Frappe--[S]", "Milk Frappe--[M]", "Milk Frappe--[L]", "Mango Milk Frappe--[S]", "Mango Milk Frappe--[M]", "Mango Milk Frappe--[L]", "Pineapple Yogurt Smoothie--[S]", "Pineapple Yogurt Smoothie--[M]", "Pineapple Yogurt Smoothie--[L]", "Strawberry Yogurt Smoothie--[S]", "Strawberry Yogurt Smoothie--[M]", "Strawberry Yogurt Smoothie--[L]", "Vanilla Ice Cream & Milk Shake--[S]", "Vanilla Ice Cream & Milk Shake--[M]", "Vanilla Ice Cream & Milk Shake--[L]" }));
        cbFood.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbFoodItemStateChanged(evt);
            }
        });

        t1.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        t1.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        t1.setEnabled(false);
        t1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t1ActionPerformed(evt);
            }
        });

        t2.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        t2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t2ActionPerformed(evt);
            }
        });

        t3.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        t3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t3ActionPerformed(evt);
            }
        });

        bn1.setText("Add");
        bn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bn1ActionPerformed(evt);
            }
        });

        bn2.setText("Delete");
        bn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bn2ActionPerformed(evt);
            }
        });

        bn3.setText("Edit");
        bn3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bn3ActionPerformed(evt);
            }
        });

        tb.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Order", "Price", "Cup", "Baht"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tb.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tb);
        if (tb.getColumnModel().getColumnCount() > 0) {
            tb.getColumnModel().getColumn(0).setResizable(false);
            tb.getColumnModel().getColumn(1).setResizable(false);
            tb.getColumnModel().getColumn(2).setResizable(false);
            tb.getColumnModel().getColumn(3).setResizable(false);
        }

        jLabel1.setFont(new java.awt.Font("Comic Sans MS", 3, 18)); // NOI18N
        jLabel1.setText("MENU");

        jLabel2.setFont(new java.awt.Font("Comic Sans MS", 3, 18)); // NOI18N
        jLabel2.setText("CUP");

        jLabel3.setFont(new java.awt.Font("Comic Sans MS", 3, 18)); // NOI18N
        jLabel3.setText("BAHT");

        jLabel4.setFont(new java.awt.Font("Comic Sans MS", 3, 18)); // NOI18N
        jLabel4.setText("TOTAL");

        lbtotal.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N

        jLabel7.setFont(new java.awt.Font("Comic Sans MS", 3, 18)); // NOI18N
        jLabel7.setText("Payment");

        jLabel8.setFont(new java.awt.Font("Comic Sans MS", 3, 18)); // NOI18N
        jLabel8.setText("change");

        tchange.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        tchange.setEnabled(false);
        tchange.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tchangeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(58, 58, 58)
                        .addComponent(cbFood, javax.swing.GroupLayout.PREFERRED_SIZE, 450, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(250, 250, 250)
                        .addComponent(jLabel1)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 52, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(54, 54, 54)
                        .addComponent(jLabel2))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(t1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(34, 34, 34)
                        .addComponent(t2, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(45, 45, 45))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(171, 171, 171)
                        .addComponent(bn1)
                        .addGap(18, 18, 18)
                        .addComponent(bn2)
                        .addGap(18, 18, 18)
                        .addComponent(bn3, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(58, 58, 58)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(110, 110, 110)
                                        .addComponent(jLabel5))
                                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(lbtotal, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
                                    .addComponent(t3)
                                    .addComponent(tchange)))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 559, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(71, 71, 71)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cbFood, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(t1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(t2, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(17, 17, 17)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(bn1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bn2, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bn3, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(lbtotal, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel7))
                    .addComponent(t3, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(tchange))
                .addGap(47, 47, 47)
                .addComponent(jLabel5)
                .addContainerGap(105, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void t1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_t1ActionPerformed

    private void bn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bn2ActionPerformed
        if(tb.isRowSelected(selected)){
            double moneySelected= Double.valueOf(tb.getValueAt(selected,3).toString().replace(",",""));
            System.out.println(moneySelected);
            total-=moneySelected;
            lbtotal.setText(""+df.format(total)+" Baht ");
            if(total==0){
                lbtotal.setText("0.00 Baht ");
            }
            model.removeRow(selected);
        }else{
            JOptionPane.showMessageDialog(this,"กรุณาเลือกรายการที่ท่านต้องการยกเลิก","คำเตือน",JOptionPane.ERROR_MESSAGE);
        }
        
    }//GEN-LAST:event_bn2ActionPerformed

    private void cbFoodItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbFoodItemStateChanged
        t1.setText(price[cbFood.getSelectedIndex()]);
    }//GEN-LAST:event_cbFoodItemStateChanged

    private void bn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bn1ActionPerformed
        Vector v=new Vector();
        if(t2.getText().isEmpty()){
            JOptionPane.showMessageDialog(this,"กรุณาใส่จำนวน","คำเตือน",JOptionPane.ERROR_MESSAGE);
        }if(checkMenu()){
            int a=Integer.parseInt(model.getValueAt(n,2).toString())+Integer.parseInt(t2.getText()); 
            model.setValueAt(a,n,2);
            double price=a*Double.valueOf(tb.getValueAt(n,1).toString());
            model.setValueAt(df.format(price),n,3);
            money=Double.valueOf(t1.getText())*Double.valueOf(t2.getText());
            total+=money;
            lbtotal.setText(""+df.format(total)+" Baht ");
        }else{       
            v.add(cbFood.getSelectedItem().toString()); 
            v.add(t1.getText());
            v.add(t2.getText());
            money=Double.valueOf(t1.getText())*Double.valueOf(t2.getText());
            v.add(df.format(money)); 
            total+=money;
            model.addRow(v);
            lbtotal.setText(""+df.format(total)+" Baht ");
    }//GEN-LAST:event_bn1ActionPerformed
}
    private void tbMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbMouseClicked
        selected = tb.getSelectedRow();
        String name=tb.getValueAt(selected,0).toString();
        System.out.println("ท่านต้องการยกเลิกเมนูที่ "+selected);
        t2.setText(tb.getValueAt(selected,2).toString());
        for(int i=0;i<cbFood.getItemCount();i++){
            if(name.equals(cbFood.getItemAt(i))){
                cbFood.setSelectedIndex(i);
            }
        }
    }//GEN-LAST:event_tbMouseClicked

    private void bn3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bn3ActionPerformed
        double before=Double.valueOf(tb.getValueAt(selected,1).toString())*Double.valueOf(tb.getValueAt(selected,2).toString());
        
        tb.setValueAt(t2.getText(),selected,2);
        int amount=Integer.valueOf(t2.getText());
        double bnew=amount*Double.valueOf(tb.getValueAt(selected, 1).toString());
        tb.setValueAt(df.format(bnew),selected,3);
        total=total-before+bnew;
        lbtotal.setText(""+df.format(total)+" Baht ");
    }//GEN-LAST:event_bn3ActionPerformed

    private void t3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t3ActionPerformed
        int pay=Integer.valueOf(t3.getText());
        if (pay>=total){
            change = pay-total;
        }else{
            JOptionPane.showMessageDialog(this,"กรุณาตรวจสอบจำนวนเงิน","คำเตือน",JOptionPane.ERROR_MESSAGE);
        }       
        System.out.println(change);
        tchange.setText(df.format(change));
    }//GEN-LAST:event_t3ActionPerformed

    private void t2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_t2ActionPerformed

    private void tchangeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tchangeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tchangeActionPerformed
    public boolean checkMenu(){
        for(int i=0;i<tb.getRowCount();i++){
            if(cbFood.getSelectedItem().toString().equals(tb.getValueAt(i,0))){
                n=i;
                System.out.println("รายการอาหารซ้ำกัน");
                return true;
            }
        }
        return false;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Form().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bn1;
    private javax.swing.JButton bn2;
    private javax.swing.JButton bn3;
    private javax.swing.JComboBox<String> cbFood;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbtotal;
    private javax.swing.JTextField t1;
    private javax.swing.JTextField t2;
    private javax.swing.JTextField t3;
    private javax.swing.JTable tb;
    private javax.swing.JTextField tchange;
    // End of variables declaration//GEN-END:variables
}
